#!/usr/bin/env bash

if [ $# -ne 1 ]; then
  >&2 echo "Usage: $0 <commit>"
  exit 1
fi

COMMIT=$(git rev-parse --short $1)

{
  GIT_SEQUENCE_EDITOR="sed -i -e 's/^pick $COMMIT/edit $COMMIT/'" git rebase -i $COMMIT~1^^ 
  GIT_COMMITTER_NAME="Mahesh K.P" GIT_COMMITTER_EMAIL="maheshp@thoughtworks.com" git commit --amend --no-edit --author="Mahesh K.P <maheshp@thoughtworks.com>"
  git rebase --continue
} &> /dev/null

echo "Mahesh is now the author of $COMMIT. You're officially off the hook.";
